- package-ecosystem: nuget
  directory: /
  groups:
    skiasharp:
      patterns:
        - SkiaSharp
        - SkiaSharp.*
  schedule:
    interval: weekly
    day: sunday
    time: "03:00"
    timezone: Europe/Oslo
  cooldown:
    default-days: 7
  commit-message:
    prefix: ${nuget_commit_prefix}
