name: 🚀 Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    name: Release Please
    if: ${{ github.event_name == 'push' }}
    uses: equinor/ops-actions/.github/workflows/release-please-manifest.yml@2198d70491e461c59dd3560b9ea10b1080d863c5 # v9.39.6
    permissions:
      contents: write
      pull-requests: write
      issues: write
