name: 🚀 Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    name: Release Please
    if: ${{ github.event_name == 'push' }}
    uses: equinor/ops-actions/.github/workflows/release-please-manifest.yml@04eae1eb46f52241507c15ab0e874b9063ccf4d0 # v9.40.1
    permissions:
      contents: write
      pull-requests: write
      issues: write
